services:
  - type: web
    name: polluted-cities-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.19.3
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - polluted-cities-backend/**
